let payload=null, lineChart=null, barChart=null;
const $=id=>document.getElementById(id);
const palette={fixed:'#ed9b73',buffer:'#b19bff',throughput:'#58b9f7',predictive:'#5ee6b9'};
Chart.defaults.color='#91a4bb';Chart.defaults.borderColor='#233249';
function update(){if(!payload)return;const alg=$('algorithm').value;const rows=payload.timelines[alg];
const labels=rows.map(x=>x.segment);if(lineChart)lineChart.destroy();lineChart=new Chart($('timeline'),{type:'line',data:{labels,datasets:[{label:'Network bandwidth',data:rows.map(x=>x.bandwidth_kbps),borderColor:'#5487ae',borderWidth:2,pointRadius:0,tension:.25},{label:alg+' bitrate',data:rows.map(x=>x.bitrate_kbps),borderColor:palette[alg],borderWidth:2,pointRadius:0,stepped:true}]},options:{responsive:true,maintainAspectRatio:false,interaction:{mode:'index',intersect:false},plugins:{legend:{position:'bottom'}},scales:{x:{title:{display:true,text:'Video segment'}},y:{beginAtZero:true,title:{display:true,text:'kbps'}}}}});
const entries=payload.algorithms;if(barChart)barChart.destroy();barChart=new Chart($('qoe'),{type:'bar',data:{labels:entries.map(x=>x.name),datasets:[{label:'QoE proxy',data:entries.map(x=>x.qoe_proxy),backgroundColor:entries.map(x=>palette[x.name]),borderRadius:5}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{y:{title:{display:true,text:'QoE proxy (arbitrary units)'}}}}});
$('rows').innerHTML=entries.map(x=>`<tr><td>${x.name}</td><td>${x.avg_bitrate_kbps}</td><td>${x.total_stall_seconds}s</td><td>${x.quality_switches}</td></tr>`).join('');
const best=[...entries].sort((a,b)=>b.qoe_proxy-a.qoe_proxy)[0];$('best').textContent=best.qoe_proxy.toFixed(2);$('best-sub').textContent=best.name+' strategy';$('stall').textContent=Math.min(...entries.map(x=>x.total_stall_seconds)).toFixed(2)+'s';$('bitrate').textContent=Math.max(...entries.map(x=>x.avg_bitrate_kbps)).toFixed(0);$('count').textContent=payload.segments;}
async function run(){const btn=$('run');btn.disabled=true;btn.textContent='Running...';try{const params=new URLSearchParams({profile:$('profile').value,segments:$('segments').value,seed:$('seed').value});const res=await fetch('/api/simulate?'+params);if(!res.ok)throw Error('Simulation failed: '+(await res.text()));payload=await res.json();update()}catch(e){alert(e.message)}finally{btn.disabled=false;btn.textContent='▶ Run simulation'}}
$('run').addEventListener('click',run);$('algorithm').addEventListener('change',update);run();
